apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.order.replicas | default .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "demo.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "demo.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: PRODUCT_GROUP
              value: "{{ .Values.catalogue.product_group }}"
            - name: SUBSCRIPTION_TYPE
              value: "{{ .Values.catalogue.subscription_type }}"
            - name: PAYMENT_MODEL
              value: "{{ .Values.billing.payment_model }}"
